version: '3'

services:
  web:
    restart: always
    build: .
    command: "sh run.sh"
    ports:
      - "8000:8000"
    volumes:
      - .:/testdeploy
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
    networks:
      - default

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    networks:
      - default

  redis:
    restart: always
    image: "redis:7.4"
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    restart: always
    build: .
    command: celery -A testdeploy worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/testdeploy
    env_file:
      - ".env"
    depends_on:
      - redis
      - db
      - web
    networks:
      - default

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /utils/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - /utils/certs/selfsigned.key:/etc/ssl/private/selfsigned.key
    depends_on:
      - web

networks:
  default: